version: '3'

services:
  dev-blockchain:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
  soltweet-build:
    depends_on: [dev-blockchain]
    build: .
    ports:
      - "3000:3000"
    command: bash -c "truffle migrate && yarn start-frontend"