version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker-compose up -d
      - run: docker-compose exec soltweet-build truffle test
      - run: docker-compose down
